---
title: "Final Project Draft"
author: Xiaoyu Li
output: github_document
---


```{r setup}
library(tidyverse)
library(readxl)
library(patchwork)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = .6,
  fig.height = 8,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Import the crime data
```{r}
crime_df = 
  read_xls(
  "./data/seven-major-felony-offenses-by-precinct-2000-2019.xls",
  range = "B3:V619") %>% 
  filter(CRIME == "TOTAL SEVEN MAJOR FELONY OFFENSES")

pct_df =
  read_xls(
  "./data/seven-major-felony-offenses-by-precinct-2000-2019.xls",
  range = "A3:A619") %>% 
  drop_na(PCT)


total_crime_df =
  crime_df %>% 
  mutate(PCT = pct_df$PCT) %>% 
  select(PCT, "2013":"2019") %>% 
  pivot_longer("2013":"2019", names_to = "year", values_to = "total_crime") %>%
  mutate(borough = case_when(
    PCT <= 34 ~ "Manhattan",
    between(PCT, 40, 52) ~ "Bronx",
    between(PCT, 60, 94) ~ "Brooklyn",
    between(PCT, 100, 115) ~ "Queens",
    between(PCT, 120, 123) ~ "Staten Island"
  )) %>%
  group_by(borough, year) %>% 
  summarize(total_crime = sum(total_crime)) %>% 
  mutate(year = as.integer(year))

write.csv(total_crime_df, "./data/total_crime.csv")
```

*"total_crime" is the total number of 7 major felonies*


Import census data

```{r}
census_df = 
  read_csv("./data/Census_Demographics_at_the_Neighborhood_Tabulation_Area__NTA__level.csv") %>% 
  select("Geographic Area - Borough", "Total Population 2010 Number") %>% 
  rename(borough = "Geographic Area - Borough",
         population_2010 = "Total Population 2010 Number"
  ) %>% 
  group_by(borough) %>% 
  summarize(population_2010 = sum(population_2010)) %>% 
  drop_na(population_2010)

write.csv(census_df, "./data/census.csv")
```


Read and tidy hiv data.
```{r}
urlfile = "https://raw.githubusercontent.com/yw3436/p8105_final.github.io/main/data/hiv_complete.csv"

hiv_df = 
  read.csv(url(urlfile))

hiv_df =
  hiv_df %>% 
  filter(sex == "All",
         sex_cat == "All",
         race_cat == "All",
         age_cat == "All",
         risk_cat == "All") %>%
  select(year, borough_cat, total_hiv_diag_N) %>% 
  filter(!borough_cat %in% c("All", "Unknown borough", "Outside NYC")) %>% 
  rename(borough = borough_cat)
  
```

Join hiv_df, total_crime_df, and census_df

```{r}
hiv_crime =
  left_join(hiv_df, total_crime_df, by = c("year", "borough"))

hiv_crime = 
  hiv_crime %>% 
  left_join(census_df, by = "borough")

hiv_crime = 
  hiv_crime %>% 
  mutate(
    hiv_diag_rate_per_10k = (total_hiv_diag_N / population_2010) * 10000,
    crime_rate_per_10k = (total_crime / population_2010) * 10000)

```

Make a plot

```{r}
hiv_crime %>% 
  ggplot(aes(x = crime_rate_per_10k, y = hiv_diag_rate_per_10k, group = borough, color = borough)) +
  geom_point()
```

plotly

```{r}
hiv_crime %>% 
  plot_ly(x = ~crime_rate_per_10k, y = ~hiv_diag_rate_per_10k, color = ~borough, type = "scatter", mode = "markers", text = ~paste('Year: ', year))
```

